version: "2"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - ${HTTP_PORT}:80
      - ${ADMIN_PORT}:81
      - ${HTTPS_PORT}:443
    networks:
      - nginxproxymanager
    volumes:
      - app_data:/data
      - letsencrypt:/etc/letsencrypt
    configs:
       - source: nginxproxymanager_config
         target: /app/config/production.json
    restart: on-failure

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    networks:
      - nginxproxymanager
    volumes:
      - db_data:/var/lib/mysql
    restart: on-failure

configs:
  nginxproxymanager_config:
    file: ./production.json

networks:
  nginxproxymanager:
    driver: overlay
    attachable: true

volumes:
    app_data:
    db_data:
    letsencrypt:
